library(lubridate)
epc <- read.delim("household_power_consumption.txt",sep=";",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings="?")
epc2 <- epc[which(epc$Date == "1/2/2007" | epc$Date == "2/2/2007"),]
epc2[,"Timestamp"] <- dmy_hms(paste(epc2[,1],epc2[,2]))
png("plot3.png")
plot(epc2$Timestamp,epc2$Sub_metering_1,xlab="",ylab="Energy sub metering",type="n",ylim=c(0,30))
points(epc2$Timestamp,epc2$Sub_metering_1,type="l",col="black")
points(epc2$Timestamp,epc2$Sub_metering_2,type="l",col="red")
points(epc2$Timestamp,epc2$Sub_metering_3,type="l",col="blue")
 legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1)
dev.off()
