library(lubridate)
epc <- read.delim("household_power_consumption.txt",sep=";",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings="?")
epc2 <- epc[which(epc$Date == "1/2/2007" | epc$Date == "2/2/2007"),]
epc2[,"Timestamp"] <- dmy_hms(paste(epc2[,1],epc2[,2]))
png("plot4.png")
par(mfrow=c(2,2))
plot(epc2$Timestamp,epc2$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l")
plot(epc2$Timestamp,epc2$Voltage,xlab="datetime",ylab="Voltage",type="l")
plot(epc2$Timestamp,epc2$Sub_metering_1,xlab="",ylab="Energy sub metering",type="n",ylim=c(0,30))
points(epc2$Timestamp,epc2$Sub_metering_1,type="l",col="black")
points(epc2$Timestamp,epc2$Sub_metering_2,type="l",col="red")
points(epc2$Timestamp,epc2$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=1)
plot(epc2$Timestamp,epc2$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()
